# Generated by Django 5.1.2 on 2024-10-22 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revision_app', '0003_sales'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sales',
            new_name='Sale',
        ),
    ]
