# Generated by Django 5.1.2 on 2024-10-22 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revision_app', '0005_alter_sale_options_products_abbreviation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='abbreviation',
            new_name='unique_key',
        ),
        migrations.RemoveField(
            model_name='products',
            name='abbreviation',
        ),
        migrations.AddField(
            model_name='products',
            name='unique_key',
            field=models.CharField(blank=True, editable=False, max_length=2, unique=True),
        ),
    ]
